 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  coco_caption: # name of the dataset builder
    dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      # annotations:
      #   train:
      #     url: /root/autodl-tmp/data/gastroscopy/hfyy/annotations_examination_conclusion/hfyy_examination_conclusion_train2.json # multi data
      #     storage: /root/autodl-tmp/data/gastroscopy/hfyy/annotations_examination_conclusion/hfyy_examination_conclusion_train2.json
      #   val:
      #     url: /root/autodl-tmp/data/gastroscopy/hfyy/annotations_examination_conclusion/hfyy_examination_conclusion_val2.json
      #     storage: /root/autodl-tmp/data/gastroscopy/hfyy/annotations_examination_conclusion/hfyy_examination_conclusion_val2.json
      #   test:
      #     url: /root/autodl-tmp/data/gastroscopy/hfyy/annotations_examination_conclusion/hfyy_examination_conclusion_test2.json
      #     storage: /root/autodl-tmp/data/gastroscopy/hfyy/annotations_examination_conclusion/hfyy_examination_conclusion_test2.json

      annotations:
        train:
          # url: /root/autodl-tmp/data/gastroscopy/hfcas/annotations_examination_conclusion/hfcas_examination_conclusion_train2.json # multi data
          # storage: /root/autodl-tmp/data/gastroscopy/hfcas/annotations_examination_conclusion/hfcas_examination_conclusion_train2.json
          # url: /root/autodl-tmp/data/gastroscopy/hfcas_hfyy_merged/hfcas_examination_conclusion_train2-hfyy_examination_conclusion_train2.json
          # storage: /root/autodl-tmp/data/gastroscopy/hfcas_hfyy_merged/hfcas_examination_conclusion_train2-hfyy_examination_conclusion_train2.json
        #   url: /root/autodl-tmp/data/gastroscopy/hfcas_hfyy_merged/hfcas_captions_multi_train2-hfyy_20240730_202301-202406_captions_multi_train-hfcas_examination_conclusion_train2-hfyy_examination_conclusion_train2.json
        #   storage: /root/autodl-tmp/data/gastroscopy/hfcas_hfyy_merged/hfcas_captions_multi_train2-hfyy_20240730_202301-202406_captions_multi_train-hfcas_examination_conclusion_train2-hfyy_examination_conclusion_train2.json
          url: /root/autodl-tmp/data/gastroscopy/hfcas_hfyy_merged/hfcas_captions_multi_train3-hfyy_20240730_202301-202406_captions_multi_train3-hfcas_examination_conclusion_train2-hfyy_examination_conclusion_train2.json
          storage: /root/autodl-tmp/data/gastroscopy/hfcas_hfyy_merged/hfcas_captions_multi_train3-hfyy_20240730_202301-202406_captions_multi_train3-hfcas_examination_conclusion_train2-hfyy_examination_conclusion_train2.json
        val:
          url: /root/autodl-tmp/data/gastroscopy/hfcas/annotations_examination_conclusion/hfcas_examination_conclusion_val2.json
          storage: /root/autodl-tmp/data/gastroscopy/hfcas/annotations_examination_conclusion/hfcas_examination_conclusion_val2.json
        test:
          url: /root/autodl-tmp/data/gastroscopy/val_sample/hfcas_examination_conclusion_val2_sample.json
          storage: /root/autodl-tmp/data/gastroscopy/val_sample/hfcas_examination_conclusion_val2_sample.json
      images:
        # storage: /root/autodl-tmp/data/gastroscopy/hfcas/images
        storage: /root/autodl-tmp/data/gastroscopy/hfcas/all_images_class7

